name: spell-check-partial

on:
  workflow_dispatch:

jobs:
  spell-check-partial:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run spell-check
        uses: autowarefoundation/autoware-github-actions/spell-check@v1
        with:
          cspell-json-url: https://raw.githubusercontent.com/kminoda/autoware-spell-check-dict/main/.cspell.json
          incremental-files-only: false
